# Generated by Django 4.1.1 on 2022-10-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('Alimentacao', 'Alimentacao'), ('Saude', 'Saude'), ('Transporte', 'Transporte'), ('Roupas', 'Roupas'), ('Moradia', 'Moradia'), ('Lazer', 'Lazer'), ('Contas mensais', 'Contas mensais'), ('Eduacacao', 'Eduacacao'), ('Imprevistos', 'Imprevistos'), ('Outros', 'Outros')], max_length=14, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('dia', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('Salario', 'Salario'), ('Venda', 'Venda'), ('Investimentos', 'Investimentos'), ('Outros', 'Outros')], max_length=13, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
                ('dia', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
